runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static

- url: /addquote.*
  script: main.app
  login: admin

- url: /.*
  script: main.app


# [END handlers]


libraries:
- name: jinja2
  version: latest


skip_files:
- ^lib/.*
- ^static/bower_components/.*